import Head from "next/head"
import { Navbar } from "../Navbar"
import styles from './MainLayout.module.css'
import Image from "next/image"

export const MainLayout = ({ children } : { children : React.ReactNode}) => {
  return (
    <>
      <Head>
        <title>Home - Uriel</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Navbar />

      <main className={styles.main}>
      

        <div className={styles.center}>
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>

        <div className='grid'>

          { children }
        </div>


      </main>
    </>
  )
}
